### PR TITLE
add alternative solution to exercise 64

### PR DESCRIPTION
**Pull request by btel**

### CODE REVIEW

**Comment by rougier** [comment]
Thanks ! Can you add your name as a comment for the alternative solution and modify the notebook as well ?

**Comment by btel** [comment]
Done. I was not sure whether to edit the markdown directly or regenerate it using nbconvert. I decided for the second solution. That's why you see a few more changes in the markdown file.

**Comment by btel** [comment]
I also integrated some changes into notebook, which were only present in the markdown file.

**Comment by rougier** [comment]
Thanks !

**Pull request merged**
