### PR TITLE
Add alternative solution for Q.19

### PR DESCRIPTION
**Pull request by HenryJi529**

### CODE REVIEW

**Comment by rougier** [comment]
Thanks

**Comment by Stefan-Heimersheim** [comment]
@rougier @HenryJi529 Just to double check, doesn't this only work for odd squares? I.e. not for 8x8?
```python
In [82]: arr = np.ones(64,dtype=int)
    ...: arr[::2]=0
    ...: arr = arr.reshape((8,8))
    ...: print(arr)
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]
```

**Comment by rougier** [comment]
Oh yes, good point. We should remove this alternative form then. Can you make a PR (or do you see how to fix it?)

**Comment by Stefan-Heimersheim** [comment]
Sure! I'll make a PR to remove it (can't see a simple or elegant way to make this work)

**Pull request merged**
