### PR TITLE
adding a simpler solution to 'sum over last two axes' exercise'

### PR DESCRIPTION
**Pull request by ibah**
Numpy.sum accepts a tuple of integers for the axis argument. This allows to apply sum over a set of axes in one go.
Jupyter notebook tested OK.

### CODE REVIEW

**Comment by rougier** [comment]
Nice. By the way, do you what is the minimum version of numpy that allows that ?

**Comment by ibah** [comment]
It was introduced in numpy 1.7.0 (found in the reference/docs for this function).

**Comment by rougier** [comment]
Worth mentioning it in the exercise ?

**Comment by ibah** [comment]
Just made a pull request to address this.

**Pull request merged**
