### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by jeremy-feng**
86. ... matrices wich shape ... -> ... matrices with shape ...

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. Actually, you only need to change `source/exercises100.ktx` and the other files will be updated.

**Comment by rougier** [comment]
Please make a PR for the typo only (and only kth file) and then you can open a new PR for the alternative solution.

**Comment by jeremy-feng** [comment]
> Please make a PR for the typo only (and only kth file) and then you can open a new PR for the alternative solution.

Ok. Please consider merging this commit: https://github.com/rougier/numpy-100/commit/683f473a6f682f0994069c22c4251971d52ff690

**Comment by rougier** [comment]
Thanks.

**Pull request merged**
