### PR TITLE
Update with corrected answer #53

### PR DESCRIPTION
**Pull request by MikeBloom914**
Switched int/float on #53

### CODE REVIEW

**Comment by rougier** [comment]
Thanks. Can you also change the .md file?

**Comment by MikeBloom914** [comment]
Yup…let me know if there is anything else :). Thanks!

**Comment by MikeBloom914** [comment]
Changed the Markdown file

**Comment by rougier** [comment]
Perfect, thanks.

**Comment by MikeBloom914** [comment]
Awesome!  No problem!

**Pull request merged**
