### PR TITLE
adding pandas solution as a reference to the 'means of subsets' exercise

### PR DESCRIPTION
**Pull request by ibah**
This type of task is more natural for panadas so I add a panadas solution as a reference.
Jupyter notebook tested ok.

### CODE REVIEW

**Comment by rougier** [comment]
Yes, but it's 100 numpy exercises...

**Comment by ibah** [comment]
Whenever the numpy solution is a bit complicated or not intuitive, I found it instructive to see a simpler solution made with a separate package specialized for the task at hand. The added value is that it tells me where to go to make things easier.
Please close the PR in case this is not what you'd like to see in the numpy-100.

**Comment by rougier** [comment]
Sorry, I was just kidding (and I forgot to merge in the process).
Thank you for your contribution

**Comment by ibah** [comment]
All is fine, no problem.

**Pull request merged**
