### PR TITLE
Q29 alternate solution

### LINKED ISSUE #87: Alternate solution to Q29
Q29. How to round away from zero a float array

Solution:
```
Z = np.random.uniform(-10, 10, 10)
Z = np.where(Z>0, np.ceil(Z), np.floor(Z))
print(Z)
```

### PR DESCRIPTION
**Pull request by acharles7**
fixes #87
provided alternate solution to Q29

### CODE REVIEW

**Comment by rougier** [comment]
Thanks.  the md/notebbok are now generated from [exercises100.ktx](https://github.com/rougier/numpy-100/blob/master/source/exercises100.ktx). Could you modify your PR?

**Comment by acharles7** [comment]
So, remove all changes from the files except  `exercises100.ktx`. Am I right?

**Comment by rougier** [comment]
Yes. Optonally, you can re-generate all the files and add them to the PR (there are some pending modifications I think).

**Comment by acharles7** [comment]
@rougier Pl have look at new changes and let me know any changes required

**Comment by rougier** [comment]
Thanks !

**Comment by mohantyk** [comment]
@acharles7 Thanks, much appreciated !

**Pull request merged**
