### PR TITLE
There was no context manager solution to go with the comment

### PR DESCRIPTION
**Pull request by Haksell**

### CODE REVIEW

**Comment by Haksell** [comment]
Sorry for the non-descriptive commit name, still new to this git thing.

**Comment by rougier** [comment]
Thanks. Since you proposed a lot of PR and each time I aksed you to regenerate the file, maybe you can do it only one for the "last" PR.

**Comment by rougier** [comment]
I'll start merging your PR and for the last, you'll regenerate the files if that's ok for you.

**Comment by Haksell** [comment]
I am not sure what you want me to do, and I am a bit worried about mixing everything up.
Could you please merge my current PRs like you want them? I will think about regenerating the files if I have modifications to make for questions 51-100.

**Pull request merged**
